suzuki-shunsuke/tfaction-docs

.github/workflows/deploy.yaml

https://github.com/suzuki-shunsuke/tfaction-docs/runs/5080909783?check_suite_focus=true

fix: fix actions-gh-pages input

---

package-lock.json
package.json

Reverts suzuki-shunsuke/tfaction-docs#6

Revert "chore(deps): update dependency @mdx-js/react to v2"

---

docs/actions/get-target-config.md
docs/actions/scaffold-tfmigrate.md
docs/actions/scaffold-working-dir.md

https://github.com/suzuki-shunsuke/tfaction/pull/331

feat: add TFACTION_WORKING_DIR

---

docs/actions/terraform-apply.md
docs/actions/terraform-plan.md
docs/actions/test.md
docs/actions/tfmigrate-apply.md
docs/actions/tfmigrate-plan.md
docs/config/add-working-directory.md
docs/config/gcp.md
docs/config/setup.md
docs/config/tfaction-root-yaml.md
docs/config/tfaction-yaml.md
docs/overview.md

https://github.com/suzuki-shunsuke/tfaction/pull/473

feat: support GCP

---

docs/actions/index.md
docs/config/config.md
docs/config/setup.md
docs/feature/follow-up-pr.md
docs/feature/module.md
docs/feature/scaffold-working-dir.md
docs/feature/skip-creating-pr.md
docs/feature/support-skipping-terraform-renovate-pr.md
docs/feature/tfmigrate.md

https://github.com/aquaproj/aquaproj.github.io/pull/231#issuecomment-1368436326

fix: change relative URLs to relative file paths

---

yarn.lock

chore: update dependencies by yarn upgrade

---

docs/config/tfaction-root-yaml.md
docs/feature/auto-update-related-prs.md

- https://github.com/suzuki-shunsuke/tfaction/issues/892

support disabling to update related prs

---

docs/feature/drift-detection.md

https://github.com/suzuki-shunsuke/tfaction/discussions/983

add a link

---

docs/feature/auto-update-related-prs.md

This PR fix grammatical errors on file auto-update-related-prs.md which is on docs/feature folder

fix errors on file auto-update-related-prs.md

---

docs/config/add-working-directory.md
docs/config/tfaction-root-yaml.md
docs/config/tfaction-yaml.md
docs/feature/plan-file.md

- https://github.com/suzuki-shunsuke/tfaction/pull/1175

migrate the storage of plan files to GitHub Actions Artifacts

---

docs/actions/apply.md
docs/actions/index.md
docs/actions/plan.md
docs/feature/auto-update-related-prs.md

- https://github.com/suzuki-shunsuke/tfaction/pull/1272
- https://github.com/suzuki-shunsuke/tfaction/pull/1275

add plan and apply action

---

docs/actions/terraform-apply.md
docs/actions/terraform-plan.md
docs/actions/tfmigrate-apply.md

AWS CLI and gsutil are unnecessary anymore.
https://github.com/suzuki-shunsuke/tfaction/releases/tag/v0.7.0

remove aws cli and gsutil from requirements

---

docs/overview.md

- https://github.com/suzuki-shunsuke/tfaction/pull/1332

Add Henry, Inc. to the list of usecases

---

docs/overview.md

- https://github.com/suzuki-shunsuke/tfaction/pull/1334

Add Macbee Planet Inc. to who-uses-tfaction

---

docs/config/tfaction-root-yaml.md
docs/feature/conftest.md

- https://github.com/suzuki-shunsuke/tfaction/pull/1519

add the document about conftest_policy_directory

---

docs/config/tfaction-root-yaml.md
docs/config/tfaction-yaml.md
docs/feature/use-terraform-compatible-tool.md
docs/overview.md

- https://github.com/suzuki-shunsuke/tfaction/pull/1554

use terraform compatible tools

---

docs/feature/follow-up-pr.md

- https://github.com/suzuki-shunsuke/tfaction/pull/1801

add the description about .tfaction/failed-prs

---

docs/feature/terraform-docs.md
docs/overview.md

https://github.com/suzuki-shunsuke/tfaction/pull/1878

terraform-docs

---

docs/feature/conftest.md

- https://github.com/suzuki-shunsuke/tfaction/pull/1914

conftest special data file

---

docs/config/tfaction-root-yaml.md
docs/config/tfaction-yaml.md

- https://github.com/suzuki-shunsuke/tfaction/pull/1930
- https://github.com/suzuki-shunsuke/tfaction/pull/1931
- https://github.com/suzuki-shunsuke/tfaction/pull/1934

AWS IAM Role session name

---

docs/config/tfaction-root-yaml.md
docs/feature/linter.md

- https://github.com/suzuki-shunsuke/tfaction/pull/2104

tflint --fix

---

.github/workflows/test.yaml
.github/workflows/wc-deploy.yaml

https://github.com/suzuki-shunsuke/batch-bulk-disable-checkout-persist-credentials/issues/1

ci: disable actions/checkout's persist-credentials using disable-checkout-persist-credentials

---

docs/config/tfaction-root-yaml.md
docs/feature/auto-fix.md
docs/feature/auto-update-related-prs.md
docs/feature/build-matrix.md
docs/feature/follow-up-pr.md
docs/feature/generate-config-out.md
docs/feature/index.md
docs/feature/limit-changed-dirs.md
docs/feature/local-path-module.md
docs/feature/plan-file.md
docs/feature/provider-dep.md
docs/feature/renovate.md
docs/feature/scaffold-working-dir.md
docs/feature/skip-creating-pr.md
docs/feature/support-skipping-terraform-renovate-pr.md
docs/feature/terraform-docs.md
docs/feature/tfcmt.md
docs/feature/use-terraform-compatible-tool.md
docusaurus.config.js
package-lock.json
package.json

- https://github.com/suzuki-shunsuke/tfaction/pull/2744

Limit changed dirs

---

docs/feature/scaffold-working-dir.md

fix: update the example
